version: "3.5"
services:
  orion:
    container_name: fiware-orion
    image: fiware/orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo
    networks:
      default:
        ipv4_address: 172.25.1.3
  mongo:
    image: mongo:3.6
    command: --nojournal
    networks:
      default:
        ipv4_address: 172.25.1.4
  keyrock:
    image: fiware/idm:7.9.0
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.25.1.5
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
      - "443:443"
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://localhost:3000
      - IDM_PORT=3000
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - IDM_DB_PASS=secret 
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234
  mysql-db:
    restart: always
    image: mysql:5.7
    hostname: mysql-db
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.25.1.6
    environment:
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=172.25.1.5"
    volumes:
      - mysql-db:/var/lib/mysql
  catcher:  
    container_name: catcher
    image: mdetools/catcher
    networks:
      default:
        ipv4_address: 172.25.1.7
  orion-proxy:  
    container_name: orion-proxy
    image: mdetools/orion-proxy
    environment:
      - "TARGET=172.25.1.3:1026"
      - "FIWARE_SERVICE_PATH=/mypath"
    networks:
      default:
        ipv4_address: 172.25.1.8
  pep-proxy-wilma:
    restart: always
    image: fiware/pep-proxy 
    container_name: fiware-wilma
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_PUBLIC_PATHS=/public
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_APP_SSL_ENABLED=false
      - PEP_PROXY_APP_PORT=80
      - PEP_PROXY_APP_HOST=172.25.1.8
      - PEP_PROXY_APP_ID=b148d72b-184b-47cd-a4e2-3b5180cb8ec6
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3000
      - PEP_PROXY_IDM_HOST=172.25.1.5
      - PEP_PROXY_PORT=8080
      - PEP_PASSWORD=pep_proxy_5c22e208-50d0-4f48-88bd-dfb943e54854
      - PEP_PROXY_USERNAME=pep_proxy_93f6133e-2491-4eb3-a305-1c372813cbab
    depends_on: 
      - keyrock
      - orion-proxy
    networks:
      default:
        ipv4_address: 172.25.1.9
networks:
  default:
    ipam:
      config:
        - subnet: 172.25.1.0/24
volumes:
  mysql-db: ~